apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-cluster-test
spec:
  replicas: 1
  # 1. Dieser Selector sagt dem Deployment, welche Pods es steuern soll
  selector:
    matchLabels:
      app: pgadmin
  # 2. Das Template definiert, wie die neuen Pods aussehen
  template:
    metadata:
      labels:
        app: pgadmin # MUSS mit dem matchLabels oben übereinstimmen!
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: cnpg-cluster-test
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080