apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-cluster-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      # Wir entfernen fsGroup komplett. OpenShift regelt das über die Namespace-Policy.
      containers:
      - name: pgadmin
        image: gcr.io/bitnami-containers/pgadmin4:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          # Wir erzwingen keine ID, sondern sagen nur: "Kein Root!"
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pgadmin-data
          mountPath: /bitnami/pgadmin
      volumes:
      - name: pgadmin-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: cnpg-cluster-test
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080