apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-cluster-test
spec:
  template:
    spec:
      securityContext:
        # OpenShift weist normalerweise zufällige UIDs zu. 
        # Wir erzwingen hier eine, die oft mit pgAdmin funktioniert.
        fsGroup: 5050 
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        # WICHTIG: Verhindert, dass das Image versucht, sudo/root zu nutzen
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 5050
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        # pgAdmin braucht ein beschreibbares Verzeichnis für Sessions
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: cnpg-cluster-test
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # Über diesen Port erreichst du es in CRC