apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-cluster-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      # Bitnami-Images laufen standardmäßig als User 1001, 
      # was perfekt in die OpenShift-Logik passt.
      securityContext:
        fsGroup: 1001
      containers:
      - name: pgadmin
        image: docker.io/bitnami/pgadmin:latest
        imagePullPolicy: IfNotPresent
        # Bitnami nutzt Port 8080 oder 1025+, damit kein Root nötig ist
        ports:
        - containerPort: 8080
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        # Bitnami nutzt diesen Pfad für Daten
        volumeMounts:
        - name: pgadmin-data
          mountPath: /bitnami/pgadmin
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      volumes:
      - name: pgadmin-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: cnpg-cluster-test
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080