apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-cluster-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      # Wir definieren KEINE feste UID. OpenShift setzt diese automatisch.
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        imagePullPolicy: IfNotPresent
        securityContext:
          # Streng nach OpenShift-Standard:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        # Wichtig: pgAdmin versucht normalerweise auf Port 80 zu lauschen. 
        # Das darf ein non-root User nicht (Ports < 1024 sind gesch체tzt).
        - name: PGADMIN_LISTEN_PORT
          value: "8080"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        # Ein emptyDir reicht f체r den Test, OpenShift setzt hier 
        # automatisch die richtigen Berechtigungen f체r den zuf채lligen User.
        emptyDir: {}
--
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: cnpg-cluster-test
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 8080 # Hier auf den neuen Container-Port zeigen
    nodePort: 30080