apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: cnpg-cluster-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: pgadmin-local:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin123"
        - name: PGADMIN_LISTEN_PORT
          value: "8080"
        # DIESER EINTRAG IST ENTSCHEIDEND:
        # Er sagt dem Entrypoint-Skript, dass es keine System-Anpassungen (chown/sudo) machen soll.
        - name: PGADMIN_CONFIG_SERVER_MODE
          value: "False" 
        securityContext:
          runAsNonRoot: true
          # OpenShift erzwingt das meistens sowieso, aber hier setzen wir es explizit:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        emptyDir: {}