---
cluster:
  version: 
    postgresql: "18"
  cluster:
    instances: 3
    storageSize: 1Gi
    storageClass: "crc-csi-hostpath-provisioner " # Wichtig für CRC/Local  
    monitoring:
      enabled: true
      prometheusRule:
          excludeRules:
            - CNPGClusterLogicalReplicationErrorsCritical
            - CNPGClusterLogicalReplicationErrors
            - CNPGClusterLogicalReplicationStoppedCritical
            - CNPGClusterLogicalReplicationStopped
      podMonitor: 
        enabled: true       
  poolers:
    - name: rw
      instances: 2
      type: rw # rw = Read/Write (Primary), ro = Read Only (Replicas)
      poolMode: transaction # Standard für die meisten Apps
      poolSize: "20"
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_label_app]
              regex: mein-postgres-cluster
              action: keep
          prometheusRule:
        excludeRules:
          - CNPGClusterLogicalReplicationErrorsCritical
          - CNPGClusterLogicalReplicationErrors
          - CNPGClusterLogicalReplicationStoppedCritical
          - CNPGClusterLogicalReplicationStopped
    - name: ro
      instances: 2
      type: ro # rw = Read/Write (Primary), ro = Read Only (Replicas)
      poolMode: transaction # Standard für die meisten Apps
      poolSize: "20"
      monitoring:
        enabled: true
        podMonitor:
          enabled: true
          relabelings:
            - sourceLabels: [__meta_kubernetes_pod_label_app]
              regex: mein-postgres-cluster
              action: keep        
grafana:
  enabled: true
  image: grafana/grafana:latest
  prometheusUrl: "https://thanos-querier.openshift-monitoring.svc.cluster.local:9091"

  

