apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster-test
  namespace: openshift-gitops
spec:
  project: 'default'
  source:
    repoURL: https://github.com/nivrelin/mein-gitops
    targetRevision: HEAD
    path: /charts/cnpg
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-cluster-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-operator
  namespace: openshift-gitops # Verweist auf Ihren funktionierenden Argo CD-Namespace
spec:
  project: default
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts' # Das offizielle Helm-Repository
    chart: cloudnative-pg
    targetRevision: 0.29.0 # Nutzen Sie die für Sie aktuell passende Chart-Version
    helm:
      values: |
        containerSecurityContext:
          runAsUser: null
          runAsGroup: null

        webhook:
          containerSecurityContext:
            runAsUser: null
            runAsGroup: null
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system # Der Ziel-Namespace für den Operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Erstellt 'cnpg-system' automatisch
      - ServerSideApply=true
