applications:
  - name: root-application
    type: github
    repoName: mein-gitops
    project: infrastructure
    targetRevision: HEAD
    path: argocd-apps
    namespace: openshift-gitops
  - name: cnpg-cluster-test
    enabled: false
    type: github
    repoName: mein-gitops
    targetRevision: HEAD
    namespace: cnpg-cluster-test
    path: charts/cnpg
    valueFiles:
      - values.yaml
  - name: grafana-instance
    enabled: false
    type: github
    namespace: monitoring-system
    repoName: GrafanaOperator
    path: .
    targetRevision: HEAD

  - name: grafana-operator
    enabled: false
    type: external
    namespace: monitoring-system
    # Für externe OCI-Charts konfigurieren wir das im Template mit (siehe Schritt 3)
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-operator
    targetRevision: 5.15.1
    inlineValues: 
      securityContext:
        runAsUser: null
        runAsGroup: null      
      containerSecurityContext:
        runAsUser: null
        runAsGroup: null
    sync:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
  - name: cnpg-operator
    enabled: false
    namespace: cnpg-operator
    type: external
    repoURL: 'https://cloudnative-pg.github.io/charts' # Das offizielle Helm-Repository
    chart: cloudnative-pg
    targetRevision: 0.29.0 # Nutzen Sie die für Sie aktuell passende Chart-Version
    inlineValues:
      containerSecurityContext:
        runAsUser: null
        runAsGroup: null
      webhook:
        containerSecurityContext:
          runAsUser: null
          runAsGroup: null
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'cnpg-system' automatisch
        - ServerSideApply=true
  - name: reloader-operator
    enabled : true
    namespace: reloader-operator
    type: external
    repoURL: 'https://stakater.github.io/stakater-charts' 
    chart: reloader
    targetRevision: 2.2.14
    inlineValues: 
      reloader:
        isOpenshift: true
        deployment: 
          securityContext:
            runAsUser: null
            runAsGroup: null      
          containerSecurityContext:
            runAsUser: null
            runAsGroup: null
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'reloader-operator' automatisch