applications:
  - name: root-application
    type: github
    repoName: mein-gitops
    project: infrastructure
    targetRevision: HEAD
    path: argocd-apps
    namespace: openshift-gitops
  - name: cnpg-cluster-test
    enabled: true
    type: github
    repoName: mein-gitops
    targetRevision: HEAD
    namespace: cnpg-cluster-test
    path: charts/cnpg
    valueFiles:
      - values.yaml
  - name: grafana-instance
    enabled: true
    type: github
    namespace: monitoring-system
    repoName: GrafanaOperator
    path: .
    targetRevision: HEAD

  - name: grafana-operator
    enabled: true
    type: external
    namespace: monitoring-system
    # Für externe OCI-Charts konfigurieren wir das im Template mit (siehe Schritt 3)
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana-operator
    targetRevision: 5.15.1
    inlineValues: 
      securityContext:
        runAsUser: null
        runAsGroup: null      
      containerSecurityContext:
        runAsUser: null
        runAsGroup: null
    sync:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
  - name: cnpg-operator
    enabled: true
    namespace: cnpg-operator
    type: external
    repoURL: 'https://cloudnative-pg.github.io/charts' # Das offizielle Helm-Repository
    chart: cloudnative-pg
    targetRevision: 0.29.0 # Nutzen Sie die für Sie aktuell passende Chart-Version
    inlineValues:
      containerSecurityContext:
        runAsUser: null
        runAsGroup: null
      webhook:
        containerSecurityContext:
          runAsUser: null
          runAsGroup: null
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'cnpg-system' automatisch
        - ServerSideApply=true
  - name: reloader-operator
    enabled : true
    namespace: reloader-operator
    type: github
    repoName: mein-gitops
    path: charts/reloader
    targetRevision: HEAD
    valueFiles:
      - values.yaml
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'reloader-operator' automatisch
  - name: redis-operator
    enabled: true
    namespace: redis-operator
    type: external
    repoURL: https://ot-container-kit.github.io/helm-charts
    chart: redis-operator
    targetRevision: v0.25.0
    inlineValues:
      replicas: 3
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'redis-operator' automatisch
        - ServerSideApply=true

  - name: redis-cluster-test
    enabled: true
    type: external
    repoURL: https://ot-container-kit.github.io/helm-charts
    chart: redis-cluster
    namespace: redis-cluster-test
    targetRevision: 0.17.4
    inlineValues:
      redisCluster:
        leader:
          pdb:
            enabled: true
        follower:
          pdb:
            enabled: true
      podSecurityContext:
        runAsUser: null
        fsGroup: null
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'redis-cluster-test' automatisch

  - name: mariadb-operator
    enabled: true
    namespace: mariadb-operator
    type: external
    repoURL: ghcr.io/mariadb-operator/charts
    chart: mariadb-operator
    targetRevision: 26.6.0
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'mariadb-operator' automatisch
  - name: mariadb-operator-crds
    enabled: true
    namespace: mariadb-operator
    type: external
    repoURL: ghcr.io/mariadb-operator/charts
    chart: mariadb-operator-crds
    targetRevision: 26.6.0
  
  - name: mariadb-cluster-test
    enabled: true
    type: external
    repoURL: ghcr.io/mariadb-operator/charts
    chart: mariadb-cluster
    namespace: mariadb-cluster-test
    targetRevision: 26.6.0
    sync:
      syncOptions:
        - CreateNamespace=true # Erstellt 'mariadb-cluster-test' automatisch
  
  - name: devspaces-operator
    enabled: true
    namespace: openshift-operators
    type: github
    repoName: devspaces
    path: .
    targetRevision: HEAD

