apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mein-postgres-cluster
  namespace: cnpg-cluster-test
spec:
  instances: 4

  # Konfiguration der Datenspeicherung
  storage:
    size: 1Gi

  # Hier war der Fehler: Tablespaces MÜSSEN eine Liste sein (mit -)
  # Wenn du keine speziellen Tablespaces brauchst, kannst du diesen Block auch löschen.
  tablespaces:
    - name: data_tablespace
      storage:
        size: 1Gi

  # Monitoring (Optional, aber empfohlen)
  monitoring:
    enablePodMonitor: true

  # Default Zertifikats-Strategie (nutzt cert-manager falls vorhanden)
  certificates:
    serverAltNames:
      - mein-postgres-cluster.cnpg.svc
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-cluster-monitor
  namespace: cnpg-cluster-test # Dein Namespace
  labels:
    # Dieses Label ist oft nötig, damit der Operator die Ressource erkennt
    release: prometheus
spec:
  selector:
    matchLabels:
      # CNPG setzt dieses Label automatisch auf alle Instanz-Pods
      cnpg.io/cluster: mein-postgres-cluster
  podMetricsEndpoints:
  - port: metrics
    interval: 30s