apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mein-postgres-cluster
  namespace: cnpg-cluster-test
spec:
  instances: 3
  postgresql:
    version: "15"
    parameters: {}
  storage:
    size: 1Gi
    storageClass: hostpath
  monitoring:
    enablePodMonitor: true
  certificates:
    serverAltNames:
      - mein-postgres-cluster.cnpg.svc
