apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name | default "mein-postgres-cluster" }}
spec:
  imageName: {{ .Values.cluster.imageName | default "ghcr.io/cloudnative-pg/postgresql:18" }}
  instances: {{ .Values.cluster.instances }}
  {{- if .Values.cluster.bootstrapFrom }}
  bootstrap:
    pg_basebackup:
      source: {{ .Values.cluster.bootstrapFrom }}
  
  externalClusters:
  {{- range .Values.cluster.externalClusters }}
    - name: {{ .name }}
      connectionParameters:
        {{- toYaml .connectionParameters | nindent 8 }}
      password:
        {{- toYaml .password | nindent 8 }}
  {{- end }}

  replica:
    enabled: {{ .Values.cluster.replicaEnabled }}
    source: {{ .Values.cluster.bootstrapFrom }}
  {{- end }}
  storage:
    size: {{ .Values.cluster.storageSize }}
    storageClass: {{ .Values.cluster.storageClass }}
  monitoring:
    enablePodMonitor: true
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.cluster.name }}-monitor
  labels:
    release: {{ .Values.monitoring.releaseLabel }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .Values.cluster.name }}
  podMetricsEndpoints:
  - port: metrics
    interval: 30s