{{- range .Values.clusters }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name }}
spec:
  # Nutzt das Image pro Cluster, Standard ist 16 falls nicht definiert
  imageName: {{ .imageName | default "ghcr.io/cloudnative-pg/postgresql:18" }}
  instances: {{ .instances | default 3 }}

  postgresql:
    pg_hba:
      - host replication postgres all md5
  bootstrap:  
    {{- if not .bootstrapFrom}}
  # Bootstrap & External Clusters (nur wenn bootstrapFrom definiert ist)
    initdb:
      database: app
      owner: app
      {{- if .initSQL}}
        postInitApplicationSQL:
          {{- range .initSQL}}
      {{- end }}
    {{- else}}
    pg_basebackup:
      source: {{ .bootstrapFrom }}
    {{- end}}
  {{- if .managed }} 
  managed:
    roles:
      {{- range .roles}} 
  {{- end}}
  {{- if .bootstrapFrom }}
  externalClusters:
    - name: {{ .bootstrapFrom }}
      connectionParameters:
        # Wir gehen davon aus, dass der Quell-Cluster im gleichen Namespace liegt
        host: {{ printf "%s-rw.%s.svc.cluster.local" .bootstrapFrom $.Release.Namespace }}
        user: postgres
      password:
        name: {{ printf "%s-superuser" .bootstrapFrom }}
        key: password

  replica:
    enabled: {{ if (hasKey . "replicaEnabled") }}{{ .replicaEnabled }}{{ else }}true{{ end }}
    source: {{ .bootstrapFrom }}
  {{- end }}

  storage:
    size: {{ .storageSize | default "1Gi" }}
    storageClass: {{ .storageClass | default "crc-csi-hostpath-provisioner" }}
  
  monitoring:
    enablePodMonitor: true
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .name }}-monitor
  labels:
    release: {{ $.Values.monitoring.releaseLabel | default "prometheus" }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .name }}
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
---
{{- end }}